include: package:lint/analysis_options.yaml

analyzer:
  enable-experiment:
    - extension-methods
  exclude:
    - lib/l10n/*.dart
    - lib/**/*.freezed.dart

linter:
  rules:
    sort_unnamed_constructors_first: false
